<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxRpuxW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxRpuxW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxRpuxW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxRpuxW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDxRpuxW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DxRpuxW',
    'container.build_id' => '9843a204',
    'container.build_time' => 1555073811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxRpuxW');
